# Generated by Django 4.2 on 2026-03-10

from django.db import migrations, models


def migrate_manager_role_to_employee(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='manager').update(role='employee')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_manager_role_to_employee, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('admin', 'Admin'), ('hr', 'HR'), ('employee', 'Employee')],
                default='employee',
                max_length=20,
            ),
        ),
    ]
